arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: localizations.dart
output-class: KaitekiLocalizations
synthetic-package: false
preferred-supported-locales: ['en']
suppress-warnings: true